name: OZIP Decrypter by TechyMinati..

on:
  watch:
    types: [started]
  workflow_dispatch:

env:
  FIRMWARE_LINK: https://rms01.realme.net/sw/RMX3261_11_A.91_20220819191422.zip
  FIRMWARE_NAME: RMX3261_11_A.91_20220819191422.zip
  TZ: Asia/Kolkata
  ARTIFACT_NAME: decrypted-firmware-${{ github.run_id }}
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Free Up Disk Space (Remove Pre-installed Stuff)
         run: |
           echo "Initial disk space:"
           df -h
           sudo rm -rf /usr/share/dotnet
           sudo rm -rf /opt/ghc
           sudo rm -rf "/usr/local/share/boost"
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
           echo "Disk space after cleanup:"
           df -h

       - name: Downloading Ozip Now..
         run: |
            sudo apt-get -qq update
            sudo apt-get install -y aria2
            echo "Downloading $FIRMWARE_NAME..."
            aria2c --console-log-level=warn --summary-interval=10 -x 16 -s 16 -k 1M "$FIRMWARE_LINK" -o "$FIRMWARE_NAME"
            echo "Download complete."

       - name: Decrypting Ozip Now
         run: |
             sudo apt-get -qq update
             sudo apt-get install -y python3-pip zip
             sudo -H pip3 install --upgrade pip
             sudo -H pip3 install --upgrade setuptools wheel docopt pycryptodome
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             echo "Decrypting $FIRMWARE_NAME..."
             sudo python3 ozipdecrypt.py "$FIRMWARE_NAME"
             echo "Decryption complete. Output in 'out' directory."
             echo "Removing original file: $FIRMWARE_NAME"
             rm -f "$FIRMWARE_NAME"
             echo "Listing contents of 'out' directory:"
             ls -lh out/

       - name: Package Decrypted Files
         run: |
          echo "Zipping contents of 'out' directory..."
          # Zip the contents *of* the 'out' directory. Create zip in workspace root.
          zip -r decrypted.zip out/*
          echo "Zipping complete: decrypted.zip created."
          ls -lh decrypted.zip # Show the created zip file size

       - name: Upload Decrypted Firmware as Artifact
         uses: actions/upload-artifact@v4
         with:
           name: ${{ env.ARTIFACT_NAME }} 
           path: decrypted.zip 
           retention-days: 5

             echo "Upload complete. Link:"

            cat links.txt
            cat links.txt
 
