name: OZIP Decrypter by TechyMinati..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  FIRMWARE_LINK: https://rms01.realme.net/sw/RMX3261_11_A.91_20220819191422.zip
  FIRMWARE_NAME: RMX3261_11_A.91_20220819191422.zip
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now.. 
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install -y python3-pip
             sudo -H pip3 install --upgrade pip 
             sudo -H pip3 install setuptools wheel docopt pycryptodome
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             sudo python3 ozipdecrypt.py $FIRMWARE_NAME
             
       - name: Upload Decrypted Zip
         run: |
          # Navigate to the out/ directory
          cd out
          # Package all decrypted files into a single ZIP
          zip -r decrypted.zip *
          # Move back to the root directory
          cd ..
          # Upload the ZIP to transfer.sh and save the link to links.txt
          curl --upload-file out/decrypted.zip https://transfer.sh/decrypted.zip > links.txt
          # Display the link in the logs
          cat links.txt
